import type {Metadata} from "next";
import {Inter as FontSans} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";
import Header from "@/components/Header";

export const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
});

export const metadata: Metadata = {
    title: "Pago de Impuesto Predial En Linea | Presidencia Municipal de Acuña",
    description: "Generated by create next ",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="es">
        <body
            className={cn("bg-background font-sans antialiased", fontSans.variable)}
        >
        <Header/>

        {children}
        </body>
        </html>
    );
}
